# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eacf461f6b5ecd9165736fa65bbab5aae9d8d5d97b6b9253457f2d2f1bee8af8f3de9a54ce1a4c83f6136c65cc4edc035e2cb027b7641b02b5f93043de6bb41b

test:
  secret_key_base: 2912ccc9efd357b1cbfa93f36cc27b2146f465245f6c82faa366ced48a98b4899e3e1d3e29a4386eceb94588d913be1b3f8559d5c3d082c59921631fa6935075

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
